In [1]:
import numpy as np

a = np.array([[10, 40], [30, 20]])

print("Original array:")
print(a)

print("Sort the array along the first axis:")
print(np.sort(a, axis=0))

print("Sort the array along the last axis:")
print(np.sort(a))

print("Sort the flattened array:")
print(np.sort(a, axis=None)) 

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


In [2]:
import numpy as np

array_3d = np.random.randint(0, 100, size=(3, 4, 5))

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 3])

selected_elements = array_3d[row_indices[:, np.newaxis], col_indices]

print('Original 3D array:\n', array_3d)
print('Row indices:\n', row_indices)
print('Column indices:\n', col_indices)
print('Selected elements:\n', selected_elements)

Original 3D array:
 [[[68 33 57 58 12]
  [65  9 29 15 45]
  [70 82 53 66 12]
  [37 55 94 47 99]]

 [[61  1 91  9 85]
  [34 46 75 36 93]
  [44 27 25 89 88]
  [21 53 56 14 66]]

 [[59 11 93 78 80]
  [24 83 27 74 11]
  [81  1 27 83 34]
  [57 95 89 71 43]]]
Row indices:
 [0 1 2]
Column indices:
 [1 2 3]
Selected elements:
 [[[65  9 29 15 45]
  [70 82 53 66 12]
  [37 55 94 47 99]]

 [[34 46 75 36 93]
  [44 27 25 89 88]
  [21 53 56 14 66]]

 [[24 83 27 74 11]
  [81  1 27 83 34]
  [57 95 89 71 43]]]
