In [1]:
import numpy as np

array_2d = np.random.randint(1, 100, size=(3, 3))

sqrt_array = np.sqrt(array_2d)

print('Original 2D array:\n', array_2d)
print('Square root of each element:\n', sqrt_array)

Original 2D array:
 [[84 32 60]
 [16 51 51]
 [96 43 66]]
Square root of each element:
 [[9.16515139 5.65685425 7.74596669]
 [4.         7.14142843 7.14142843]
 [9.79795897 6.55743852 8.1240384 ]]


In [2]:
import numpy as np  

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mask = np.array([False, True, False, True, False, True, False, True, False, True])

masked_array = np.ma.masked_array(data, mask=mask)

filled_array = np.ma.filled(masked_array, fill_value=-1)

print("Original Masked Array:")
print(masked_array)

print("\nFilled Array:")
print(filled_array)

Original Masked Array:
[1 -- 3 -- 5 -- 7 -- 9 --]

Filled Array:
[ 1 -1  3 -1  5 -1  7 -1  9 -1]
