In [1]:
import numpy as np

matrix = np.identity(3)
print("3x3 identity matrix:")
print(matrix)

vert_stack = np.vstack((matrix, matrix, matrix))

horz_stack = np.hstack((matrix, matrix, matrix))
print("Vertical Stack:\n", vert_stack)
print("Horizontal Stack:\n", horz_stack)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vertical Stack:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Horizontal Stack:
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [2]:
import numpy as np

matrix = np.random.random((3, 4))

max_value_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_value = np.min(matrix)

matrix[max_value_index] = min_value

print(matrix)

[[0.83434697 0.72450826 0.38358792 0.82762704]
 [0.1064208  0.27276706 0.1064208  0.62490058]
 [0.51928544 0.89155091 0.56529199 0.61221487]]
