# Task: Multidimensional Array Slicer

## Problem Statement
Write a Python function that takes a **multidimensional NumPy array** and slices the **first two elements from the third dimension**. This is useful when you want to reduce or extract specific components from a 3D dataset (e.g., images, tensors, etc.).

## Steps
1. Import the `numpy` module as `np`.
2. Define a function `slice_third_dimension(arr)`:
   - Use NumPy slicing syntax `arr[..., :2]` to retain all rows and columns, but slice only the **first two elements** of the third axis.
3. Create a sample 3D NumPy array (`nums`) for demonstration.
4. Call the slicing function and print both the **original** and the **sliced** array to observe the transformation.


In [1]:
import numpy as np

In [2]:
def slice_third_dimension(arr):
    return arr[..., :2]

In [3]:
nums = np.array([[[1, 2, 3], [4, 5, 6]],
                           [[7, 8, 9], [10, 11, 12]],
                           [[13, 14, 15], [16, 17, 18]]])

In [4]:
print("Original multidimensional array:")
print(nums)

Original multidimensional array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [5]:
sliced_array = slice_third_dimension(nums)

In [6]:
print("\nSlices the first two elements from the said array:")
print(sliced_array)


Slices the first two elements from the said array:
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]
