In [3]:
import numpy as np

rand_num = np.random.normal(0, 1, 15)

print("15 random numbers from a standard normal distribution:")

print(rand_num) 

15 random numbers from a standard normal distribution:
[ 0.08340595  0.62917035  1.03913507 -0.75029984  0.14175947  0.81512745
 -0.74676318 -0.55845119  0.79380802  0.20965476 -0.56374815 -0.58820951
  0.44200997 -0.95039539  0.11224036]


In [4]:
import numpy as np

array_2D = np.identity(3)

print('3x3 matrix:')

print(array_2D) 

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np

a = [1, 2, 3, 4]
print("Original array")
print(a)

print("Repeating 2 times")
x = np.tile(a, 2)
print(x)

print("Repeating 3 times")
x = np.tile(a, 3)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]
